_wandb:
    value:
        cli_version: 0.23.1
        e:
            b8gkyo3l4yhguwdsa00cu2pwxngdayh7:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "3221225472"
                codePath: /Users/ndeyeawasalane/Downloads/DL/miniproject2_language_model/my_model.ipynb
                codePathLocal: my_model.ipynb
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "228012830720"
                email: awasalane7@gmail.com
                executable: /Users/ndeyeawasalane/Downloads/DL/miniproject2_language_model/venv/bin/python
                git:
                    commit: 18eacce8d85e4d07083661315f8b6b1ad5fdaf41
                    remote: https://github.com/acoderwannabe19/miniproject-2-language-model.git
                host: Ndeyes-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/ndeyeawasalane/Downloads/DL/miniproject2_language_model/my_model.ipynb
                python: CPython 3.13.7
                root: /Users/ndeyeawasalane/Downloads/DL/miniproject2_language_model
                startedAt: "2025-12-10T18:19:06.074941Z"
                writerId: b8gkyo3l4yhguwdsa00cu2pwxngdayh7
        m: []
        python_version: 3.13.7
        t:
            "2":
                - 1
            "3":
                - 2
            "4": 3.13.7
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": darwin-arm64
